import { ColorKeys } from "./types";

export const OneHunterColorsObject: Record<ColorKeys, ColorKeys> = {
  white: "white",
  blackBase: "blackBase",
  blackDark: "blackDark",
  pinkBase: "pinkBase",
  pinkOnActive: "pinkOnActive",
  blueBase: "blueBase",
  blueOnActive: "blueOnActive",
  blueDark: "blueDark",
  blueDarkOnActive: "blueDarkOnActive",
  purpleBase: "purpleBase",
  purpleOnActive: "purpleOnActive",
  yellowBase: "yellowBase",
  cyanBase: "cyanBase",
  cyanOnActive: "cyanOnActive",
  grayDarkBase: "grayDarkBase",
  grayDarkOnHover: "grayDarkOnHover",
  grayDarkOnFocus: "grayDarkOnFocus",
  grayDarkOnActive: "grayDarkOnActive",
  grayLight: "grayLight",
  grayMedium: "grayMedium",
  gray: "gray",
  graySoft: "graySoft",
  red: "red",
  slate: "slate",
  green: "green",
  redDark: "redDark",
  greenLight: "greenLight",
  yellowLight: "yellowLight",
  grayBlue: "grayBlue",
  blueSoft: "blueSoft",
  brown: "brown",
  blackBlue: "blackBlue",
  info: "info",
  warn: "warn",
  error: "error",
  debug: "debug",
  "meta.object-literal.key.tsx": "meta.object-literal.key.tsx",
  "entity.name.tag.tsx": "entity.name.tag.tsx",
  "support.class.component.tsx": "support.class.component.tsx",
  "keyword-weight": "keyword-weight",
};
