import { ColorKeys, FlexokiColorPallete } from "./types";

export const OneHunterColorsObject: Record<ColorKeys, ColorKeys> = {
  white: "white",
  blackBase: "blackBase",
  blackDark: "blackDark",
  pinkBase: "pinkBase",
  pinkOnActive: "pinkOnActive",
  blueBase: "blueBase",
  blueOnActive: "blueOnActive",
  blueDark: "blueDark",
  blueDarkOnActive: "blueDarkOnActive",
  purpleBase: "purpleBase",
  purpleOnActive: "purpleOnActive",
  yellowBase: "yellowBase",
  cyanBase: "cyanBase",
  cyanOnActive: "cyanOnActive",
  grayDarkBase: "grayDarkBase",
  grayDarkOnHover: "grayDarkOnHover",
  grayDarkOnFocus: "grayDarkOnFocus",
  grayDarkOnActive: "grayDarkOnActive",
  grayLight: "grayLight",
  grayMedium: "grayMedium",
  gray: "gray",
  graySoft: "graySoft",
  red: "red",
  slate: "slate",
  green: "green",
  redDark: "redDark",
  greenLight: "greenLight",
  yellowLight: "yellowLight",
  grayBlue: "grayBlue",
  blueSoft: "blueSoft",
  brown: "brown",
  blackBlue: "blackBlue",
  info: "info",
  warn: "warn",
  error: "error",
  debug: "debug",
  "meta.object-literal.key.tsx": "meta.object-literal.key.tsx",
  "entity.name.tag.tsx": "entity.name.tag.tsx",
  "support.class.component.tsx": "support.class.component.tsx",
  "keyword-weight": "keyword-weight",
};

export const FlexokiColorsObject: Record<
  FlexokiColorPallete,
  FlexokiColorPallete
> = {
  bg: "bg",
  "bg-2": "bg-2",
  ui: "ui",
  "ui-2": "ui-2",
  "ui-3": "ui-3",
  tx: "tx",
  "tx-2": "tx-2",
  "tx-3": "tx-3",
  re: "re",
  "re-2": "re-2",
  or: "or",
  "or-2": "or-2",
  ye: "ye",
  "ye-2": "ye-2",
  gr: "gr",
  "gr-2": "gr-2",
  cy: "cy",
  "cy-2": "cy-2",
  bl: "bl",
  "bl-2": "bl-2",
  pu: "pu",
  "pu-2": "pu-2",
  ma: "ma",
  "ma-2": "ma-2",
};
