import { FlexokiColorsObject } from "../data";

export const flexokiEditorTheme = {
  "editor.background": FlexokiColorsObject["bg"],
  "editor.foreground": FlexokiColorsObject.tx,
  "editor.hoverHighlightBackground": FlexokiColorsObject["ui-2"],
  "editor.lineHighlightBackground": FlexokiColorsObject["bg"],
  "editor.selectionBackground": FlexokiColorsObject["ui-3"],
  "editor.wordHighlightBackground": FlexokiColorsObject["ui-2"],
  "editor.wordHighlightStrongBackground": FlexokiColorsObject["ui-3"],
  "editorBracketMatch.background": FlexokiColorsObject["ui-2"],
  "editorBracketMatch.border": FlexokiColorsObject["ui-2"],
  "editorCursor.foreground": FlexokiColorsObject.tx,
  "editorGutter.addedBackground": FlexokiColorsObject.gr,
  "editorGutter.background": FlexokiColorsObject["bg"],
  "editorGutter.deletedBackground": FlexokiColorsObject.re,
  "editorGutter.modifiedBackground": FlexokiColorsObject.bl,
  "editorIndentGuide.background": FlexokiColorsObject.ui,
  "editorInlayHint.background": FlexokiColorsObject["bg"],
  "editorInlayHint.foreground": FlexokiColorsObject.tx,
  "editorLineNumber.foreground": FlexokiColorsObject["tx-2"],
  "editorLineNumber.background": FlexokiColorsObject["bg"],
  "editorLink.activeForeground": FlexokiColorsObject.bl,
  "editorOverviewRuler.addedForeground": FlexokiColorsObject["gr-2"],
  "editorOverviewRuler.deletedForeground": FlexokiColorsObject["re-2"],
  "editorOverviewRuler.errorForeground": FlexokiColorsObject["re-2"],
  "editorOverviewRuler.findMatchForeground": FlexokiColorsObject["bl-2"],
  "editorOverviewRuler.infoForeground": FlexokiColorsObject["bl-2"],
  "editorOverviewRuler.modifiedForeground": FlexokiColorsObject["bl-2"],
  "editorOverviewRuler.warningForeground": FlexokiColorsObject["ye-2"],
  "editorRuler.foreground": FlexokiColorsObject.ui,
  "editorSuggestWidget.foreground": FlexokiColorsObject.tx,
  "editorSuggestWidget.highlightForeground": FlexokiColorsObject["ma-2"],
  "editorSuggestWidget.selectedBackground": FlexokiColorsObject["tx-3"],
  "editorWhitespace.foreground": FlexokiColorsObject["ui-3"],
  "editorWidget.background": FlexokiColorsObject["ui-2"],
  "editorWidget.border": FlexokiColorsObject["ui-2"],

  /* Sidebar */
  "sideBar.background": FlexokiColorsObject["bg-2"],
  "sideBar.foreground": FlexokiColorsObject.tx,
  "sideBar.border": FlexokiColorsObject["ui-2"],
  "sideBarSectionHeader.background": FlexokiColorsObject["bg-2"],
  "sideBarSectionHeader.foreground": FlexokiColorsObject.tx,
  "sideBarSectionHeader.border": FlexokiColorsObject["ui-2"],

  /* Files list */
  "badge.background": FlexokiColorsObject["bl-2"],
  "badge.foreground": FlexokiColorsObject["bg"],
  "list.activeSelectionBackground": FlexokiColorsObject["tx-3"],
  "list.activeSelectionForeground": FlexokiColorsObject.tx,
  "list.focusBackground": FlexokiColorsObject.ui,
  "list.hoverBackground": FlexokiColorsObject["ui-2"],
  "list.inactiveSelectionBackground": FlexokiColorsObject["ui"],

  /* Title bar */
  "titleBar.activeBackground": FlexokiColorsObject["bg-2"],
  "titleBar.border": FlexokiColorsObject["ui-2"],

  /* Activity bar */
  "activityBar.background": FlexokiColorsObject["bg-2"],
  "activityBar.foreground": FlexokiColorsObject.tx,
  "activityBar.border": FlexokiColorsObject["ui-2"],
  "activityBarBadge.background": FlexokiColorsObject["bl-2"],
  "activityBarBadge.foreground": FlexokiColorsObject["bg"],

  /* Tabs */
  "editorGroupHeader.tabsBackground": FlexokiColorsObject["bg-2"],
  "tab.inactiveBackground": FlexokiColorsObject["bg-2"],
  "tab.inactiveForeground": FlexokiColorsObject["tx-2"],
  "tab.activeModifiedBorder": FlexokiColorsObject["ye-2"],
  "tab.inactiveModifiedBorder": FlexokiColorsObject["bl-2"],
  "tab.unfocusedActiveModifiedBorder": FlexokiColorsObject["ye"],
  "tab.unfocusedInactiveModifiedBorder": FlexokiColorsObject["bl"],
  "tab.border": FlexokiColorsObject["ui-2"],

  /* Terminal */
  "terminal.ansiBlack": FlexokiColorsObject["bg"],
  "terminal.ansiBlue": FlexokiColorsObject["bl-2"],
  "terminal.ansiBrightBlack": FlexokiColorsObject["ui-2"],
  "terminal.ansiBrightBlue": FlexokiColorsObject["bl-2"],
  "terminal.ansiBrightCyan": FlexokiColorsObject["cy-2"],
  "terminal.ansiBrightGreen": FlexokiColorsObject["gr-2"],
  "terminal.ansiBrightMagenta": FlexokiColorsObject["ma-2"],
  "terminal.ansiBrightRed": FlexokiColorsObject["re-2"],
  "terminal.ansiBrightWhite": FlexokiColorsObject.tx,
  "terminal.ansiBrightYellow": FlexokiColorsObject["ye-2"],
  "terminal.ansiCyan": FlexokiColorsObject.cy,
  "terminal.ansiGreen": FlexokiColorsObject.gr,
  "terminal.ansiMagenta": FlexokiColorsObject.ma,
  "terminal.ansiRed": FlexokiColorsObject.re,
  "terminal.ansiWhite": FlexokiColorsObject.tx,
  "terminal.ansiYellow": FlexokiColorsObject.ye,
  "terminal.background": FlexokiColorsObject["bg-2"],
  "terminal.foreground": FlexokiColorsObject.tx,

  /* Git */
  "gitDecoration.conflictingResourceForeground": FlexokiColorsObject["or-2"],
  "gitDecoration.deletedResourceForeground": FlexokiColorsObject["re-2"],
  "gitDecoration.ignoredResourceForeground": FlexokiColorsObject["tx-3"],
  "gitDecoration.modifiedResourceForeground": FlexokiColorsObject["ye-2"],
  "gitDecoration.untrackedResourceForeground": FlexokiColorsObject["cy-2"],

  /* Status bar */
  "statusBar.background": FlexokiColorsObject["bg-2"],
  "statusBar.foreground": FlexokiColorsObject.tx,
  "statusBar.border": FlexokiColorsObject["ui-2"],
  "statusBar.noFolderBackground": FlexokiColorsObject["ui-2"],

  /* Scrollbar */
  "scrollbar.shadow": FlexokiColorsObject["ui-2"],
  "scrollbarSlider.activeBackground": FlexokiColorsObject.ui,
  "scrollbarSlider.background": FlexokiColorsObject["ui-3"],
  "scrollbarSlider.hoverBackground": FlexokiColorsObject["tx-3"],

  /* Misc */
  "button.background": FlexokiColorsObject["bl-2"],
  "button.foreground": FlexokiColorsObject["bg"],
  "dropdown.background": FlexokiColorsObject.ui,
  "dropdown.border": FlexokiColorsObject["ui-3"],
  "dropdown.foreground": FlexokiColorsObject.tx,
  "extensionButton.prominentBackground": FlexokiColorsObject["gr-2"],
  "extensionButton.prominentForeground": FlexokiColorsObject.tx,
  "extensionButton.prominentHoverBackground": FlexokiColorsObject["gr-2"],
  focusBorder: FlexokiColorsObject["bl-2"],
  foreground: FlexokiColorsObject.tx,
  "input.background": FlexokiColorsObject["ui-3"],
  "input.border": FlexokiColorsObject["ui-2"],
  "input.foreground": FlexokiColorsObject.tx,
  "input.placeholderForeground": FlexokiColorsObject["tx-2"],
  "inputOption.activeBorder": FlexokiColorsObject["bl-2"],
  "panel.background": FlexokiColorsObject["ui"],
  "panel.border": FlexokiColorsObject["ui-2"],
  "panelTitle.activeBorder": FlexokiColorsObject["bl-2"],
  "panelTitle.inactiveForeground": FlexokiColorsObject["tx-2"],
  "peekView.border": FlexokiColorsObject["ui-2"],
  "peekViewEditor.background": FlexokiColorsObject.ui,
  "peekViewEditor.matchHighlightBackground": FlexokiColorsObject["tx-3"],
  "peekViewEditorGutter.background": FlexokiColorsObject["ui-2"],
  "peekViewResult.background": FlexokiColorsObject["ui-3"],
  "peekViewResult.fileForeground": FlexokiColorsObject.tx,
  "peekViewResult.lineForeground": FlexokiColorsObject["tx-2"],
  "peekViewResult.matchHighlightBackground": FlexokiColorsObject["ui-2"],
  "peekViewResult.selectionBackground": FlexokiColorsObject["tx-3"],
  "peekViewResult.selectionForeground": FlexokiColorsObject.tx,
  "peekViewTitle.background": FlexokiColorsObject["tx-3"],
  "peekViewTitleDescription.foreground": FlexokiColorsObject["tx-3"],
  "peekViewTitleLabel.foreground": FlexokiColorsObject.tx,
  "progressBar.background": FlexokiColorsObject["bl-2"],
};
